stages:
  # - docker-build
  - deploy


# docker-build:
#   stage: docker-build
#   image: jdrouet/docker-with-buildx:latest
#   services:
#     - docker:dind
#   before_script:
#     - echo $CI_REGISTRY_PASSWORD |docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
#   script:
#     - docker buildx create --name mybuilder
#     - docker buildx use mybuilder
#     - docker buildx build --pull --platform linux/arm64 -t $CI_REGISTRY_IMAGE --push .
#     - docker buildx prune -a -f
#     - echo "Registry image:" $CI_REGISTRY_IMAGE
#   only:
#     - main

#deploy with ssh key

deploy:
  stage: deploy
  image: dannranny/ssh-agent:latest
  before_script:
    - chmod 600 $SSH_PRIVATE_KEY
  script:
    
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$SERVER_IP "echo $CI_REGISTRY_PASSWORD |docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin;  cd docopypaste_react;docker pull  ; docker-compose up -d"
  only:
    - main                                                                                                                                                                            




