stages:
  - deploy

deploy:
  stage: deploy
  image: linuxserver/openssh-server
  script:
    - echo $SSH_KEY > id_rsa
    - chmod 400 id_rsa
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$SERVER_IP "  cd copypaste_react; sh deploy.sh"
  only:
    - main                                                                                                                                                                            




