stages:
  - docker-build
  - deploy


docker-build:
  stage: docker-build
  image: jdrouet/docker-with-buildx:latest
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD |docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker buildx create --use --name mybuilder
    - docker buildx inspect --bootstrap
    - docker buildx ls
    - docker buildx build --pull --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE --push .
    - docker buildx prune -a -f
    - echo "Registry image:" $CI_REGISTRY_IMAGE
  only:
    - main

#deploy with ssh key

deploy:
  stage: deploy
  image: dannranny/ssh-agent:latest
  before_script:
    - chmod 600 $SSH_PRIVATE_KEY
  script:
    
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@$SERVER_HOST_NAME "echo $CI_REGISTRY_PASSWORD |docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin; sudo docker pull registry.gitlab.com/do-copypaste/copypaste_node:latest ; cd copypaste_node; docker-compose up -d"
  only:
    - main                                                                                                                                                                            




