name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check branch
        run: echo ${{ github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: check all files
        run: ls

      - name: Install dependencies
        run: npm ci
    
      - name: Build the app
        run: npm run build
        env:
          CI: false
          REACT_APP_PUBLIC_POSTHOG_KEY: ${{ secrets.REACT_APP_PUBLIC_POSTHOG_KEY }} 
          REACT_APP_PUBLIC_POSTHOG_HOST: ${{ secrets.REACT_APP_PUBLIC_POSTHOG_HOST }} 
      - name: install firebase tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run : firebase deploy --only hosting:${{ github.ref_name }} --token ${{ secrets.FIREBASE_TOKEN }}